// Code generated by oagen. DO NOT EDIT.

use crate::client::Client;
#[allow(unused_imports)]
use crate::enums::*;
use crate::error::Error;
#[allow(unused_imports)]
use crate::models::*;
use serde::Serialize;

pub struct OrganizationsApi<'a> {
    pub(crate) client: &'a Client,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct ListOrganizationsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub before: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order: Option<PaginationOrder>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domains: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub search: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct CreateOrganizationParams {
    #[serde(skip)]
    pub body: OrganizationInput,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct GetOrganizationByExternalIdParams {}

#[derive(Debug, Clone, Default, Serialize)]
pub struct GetOrganizationParams {}

#[derive(Debug, Clone, Serialize)]
pub struct UpdateOrganizationParams {
    #[serde(skip)]
    pub body: UpdateOrganization,
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct DeleteOrganizationParams {}

#[derive(Debug, Clone, Default, Serialize)]
pub struct GetAuditLogConfigurationParams {}

impl<'a> OrganizationsApi<'a> {
    /// List Organizations
    ///
    /// Get a list of all of your existing organizations matching the criteria specified.
    pub async fn list_organizations(
        &self,
        params: ListOrganizationsParams,
    ) -> Result<OrganizationList, Error> {
        let path = "/organizations".to_string();
        let method = reqwest::Method::GET;
        self.client.request_with_query(method, &path, &params).await
    }

    /// Create an Organization
    ///
    /// Creates a new organization in the current environment.
    pub async fn create_organization(
        &self,
        params: CreateOrganizationParams,
    ) -> Result<Organization, Error> {
        let path = "/organizations".to_string();
        let method = reqwest::Method::POST;
        self.client
            .request_with_body(method, &path, &params, Some(&params.body))
            .await
    }

    /// Get an Organization by External ID
    ///
    /// Get the details of an existing organization by an [external identifier](https://workos.com/docs/authkit/metadata/external-identifiers).
    pub async fn get_organization_by_external_id(
        &self,
        external_id: &str,
        params: GetOrganizationByExternalIdParams,
    ) -> Result<Organization, Error> {
        let path = format!("/organizations/external_id/{}", external_id);
        let method = reqwest::Method::GET;
        self.client.request_with_query(method, &path, &params).await
    }

    /// Get an Organization
    ///
    /// Get the details of an existing organization.
    pub async fn get_organization(
        &self,
        id: &str,
        params: GetOrganizationParams,
    ) -> Result<Organization, Error> {
        let path = format!("/organizations/{}", id);
        let method = reqwest::Method::GET;
        self.client.request_with_query(method, &path, &params).await
    }

    /// Update an Organization
    ///
    /// Updates an organization in the current environment.
    pub async fn update_organization(
        &self,
        id: &str,
        params: UpdateOrganizationParams,
    ) -> Result<Organization, Error> {
        let path = format!("/organizations/{}", id);
        let method = reqwest::Method::PUT;
        self.client
            .request_with_body(method, &path, &params, Some(&params.body))
            .await
    }

    /// Delete an Organization
    ///
    /// Permanently deletes an organization in the current environment. It cannot be undone.
    pub async fn delete_organization(
        &self,
        id: &str,
        params: DeleteOrganizationParams,
    ) -> Result<serde_json::Value, Error> {
        let path = format!("/organizations/{}", id);
        let method = reqwest::Method::DELETE;
        self.client.request_with_query(method, &path, &params).await
    }

    /// Get Audit Log Configuration
    ///
    /// Get the unified view of audit log trail and stream configuration for an organization.
    pub async fn get_audit_log_configuration(
        &self,
        id: &str,
        params: GetAuditLogConfigurationParams,
    ) -> Result<AuditLogConfiguration, Error> {
        let path = format!("/organizations/{}/audit_log_configuration", id);
        let method = reqwest::Method::GET;
        self.client.request_with_query(method, &path, &params).await
    }
}
