// Code generated by oagen. DO NOT EDIT.

use crate::client::Client;
#[allow(unused_imports)]
use crate::enums::*;
use crate::error::Error;
#[allow(unused_imports)]
use crate::models::*;
use serde::Serialize;

pub struct WidgetsApi<'a> {
    pub(crate) client: &'a Client,
}

#[derive(Debug, Clone, Serialize)]
pub struct CreateTokenParams {
    #[serde(skip)]
    pub body: WidgetSessionToken,
}

impl<'a> WidgetsApi<'a> {
    /// Generate a widget token
    ///
    /// Generate a widget token scoped to an organization and user with the specified scopes.
    pub async fn create_token(
        &self,
        params: CreateTokenParams,
    ) -> Result<WidgetSessionTokenResponse, Error> {
        let path = "/widgets/token".to_string();
        let method = reqwest::Method::POST;
        self.client
            .request_with_body(method, &path, &params, Some(&params.body))
            .await
    }
}
