// Code generated by oagen. DO NOT EDIT.

mod common;

use wiremock::matchers::{method, path as path_matcher};
use wiremock::{Mock, MockServer, ResponseTemplate};

#[tokio::test]
async fn directory_sync_list_directories_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/directories"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/directory_list.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .directory_sync()
        .list_directories(workos::directory_sync::ListDirectoriesParams::default())
        .await;
}

#[tokio::test]
async fn directory_sync_get_directory_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/directories/test_id"))
        .respond_with(
            ResponseTemplate::new(200).set_body_string(include_str!("fixtures/directory.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client.directory_sync().get_directory("test_id").await;
}

#[tokio::test]
async fn directory_sync_delete_directory_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("DELETE"))
        .and(path_matcher("/directories/test_id"))
        .respond_with(ResponseTemplate::new(200).set_body_string("{}"))
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client.directory_sync().delete_directory("test_id").await;
}

#[tokio::test]
async fn directory_sync_list_groups_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/directory_groups"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/directory_group_list.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .directory_sync()
        .list_groups(workos::directory_sync::ListGroupsParams::default())
        .await;
}

#[tokio::test]
async fn directory_sync_get_group_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/directory_groups/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/directory_group.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client.directory_sync().get_group("test_id").await;
}

#[tokio::test]
async fn directory_sync_list_users_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/directory_users"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/directory_user_list.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client
        .directory_sync()
        .list_users(workos::directory_sync::ListUsersParams::default())
        .await;
}

#[tokio::test]
async fn directory_sync_get_user_round_trip() {
    let server = MockServer::start().await;
    Mock::given(method("GET"))
        .and(path_matcher("/directory_users/test_id"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_string(include_str!("fixtures/directory_user_with_groups.json")),
        )
        .expect(1)
        .mount(&server)
        .await;
    let client = common::test_client(&server).await;
    let _ = client.directory_sync().get_user("test_id").await;
}
