// This file is auto-generated by oagen. Do not edit.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum RadarStandaloneResponseBlocklistType {
    IpAddress,
    Domain,
    Email,
    Device,
    UserAgent,
    DeviceFingerprint,
    Country,
    /// Wire value not recognized by this SDK version. The original
    /// string is preserved verbatim. WorkOS may add new enum values
    /// server-side; matching on this variant lets callers handle
    /// forward-compatible values without panicking.
    Unknown(String),
}

impl RadarStandaloneResponseBlocklistType {
    /// Canonical wire string for this value. For [`Self::Unknown`] returns the
    /// original wire value as received from the API.
    #[allow(deprecated)]
    pub fn as_str(&self) -> &str {
        match self {
            Self::IpAddress => "ip_address",
            Self::Domain => "domain",
            Self::Email => "email",
            Self::Device => "device",
            Self::UserAgent => "user_agent",
            Self::DeviceFingerprint => "device_fingerprint",
            Self::Country => "country",
            Self::Unknown(s) => s.as_str(),
        }
    }
}

impl fmt::Display for RadarStandaloneResponseBlocklistType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl AsRef<str> for RadarStandaloneResponseBlocklistType {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl FromStr for RadarStandaloneResponseBlocklistType {
    type Err = std::convert::Infallible;
    #[allow(deprecated)]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            "ip_address" => Self::IpAddress,
            "domain" => Self::Domain,
            "email" => Self::Email,
            "device" => Self::Device,
            "user_agent" => Self::UserAgent,
            "device_fingerprint" => Self::DeviceFingerprint,
            "country" => Self::Country,
            other => Self::Unknown(other.to_string()),
        })
    }
}

impl From<String> for RadarStandaloneResponseBlocklistType {
    fn from(s: String) -> Self {
        // Reuse the original `String` allocation in the fallback branch.
        match Self::from_str(&s) {
            Ok(Self::Unknown(_)) => Self::Unknown(s),
            Ok(other) => other,
        }
    }
}

impl From<&str> for RadarStandaloneResponseBlocklistType {
    fn from(s: &str) -> Self {
        Self::from_str(s).unwrap_or_else(|_| Self::Unknown(s.to_string()))
    }
}

impl Serialize for RadarStandaloneResponseBlocklistType {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for RadarStandaloneResponseBlocklistType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}
