// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRegistrationClaim {
    /// Unique identifier of the claim.
    pub id: String,
    /// The completion record for the claim, or `null` if the claim has not been completed.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub claim_completion: Option<AgentRegistrationClaimClaimCompletion>,
    /// The timestamp when the claim was created.
    pub created_at: String,
    /// The timestamp when the claim was last updated.
    pub updated_at: String,
    /// The timestamp when the claim expires.
    pub expires_at: String,
}
