// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Who may mint sessions from this blueprint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentBlueprintInvocableBy {
    /// Role slugs whose members may mint user-delegated sessions from this blueprint.
    pub role_slugs: Vec<String>,
    /// Organizations in which sessions may be minted from this blueprint, enforced on user-delegated, autonomous, and agent-delegated mints.
    pub organization_ids: Vec<String>,
}
