// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRegistrationClaimAttemptCreatedData {
    /// Distinguishes the agent registration claim attempt object.
    pub object: String,
    /// Unique identifier of the agent registration claim attempt.
    pub id: String,
    /// The ID of the agent registration.
    pub agent_registration_id: String,
    /// The ID of the agent registration claim.
    pub agent_registration_claim_id: String,
    /// The login hint for the claim attempt.
    pub login_hint: String,
    /// The timestamp when the claim attempt expires.
    pub expires_at: String,
    /// The timestamp when the claim attempt was created.
    pub created_at: String,
    /// The timestamp when the claim attempt was last updated.
    pub updated_at: String,
}
