// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The agent identity for this registration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentRegistrationCreatedDataAgentIdentity {
    /// Distinguishes the agent identity object.
    pub object: String,
    /// Unique identifier of the agent identity.
    pub id: String,
    /// The ID of the userland user bound to this agent identity.
    pub userland_user_id: AgentRegistrationClaimCompletedDataClaimedByOrganizationIdOneOf,
}
