// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditLogsRetentionJson {
    /// The number of days Audit Log events will be retained before being permanently deleted. Valid values are 30 and 365.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub retention_period_in_days: Option<i64>,
}
