// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditLogConfiguration {
    /// Unique identifier of the Organization.
    pub organization_id: String,
    /// The number of days Audit Log events will be retained before being permanently deleted.
    pub retention_period_in_days: i64,
    /// The current state of the audit log configuration for the organization.
    pub state: AuditLogConfigurationState,
    /// The Audit Log Stream currently configured for the organization, if any.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub log_stream: Option<AuditLogConfigurationLogStream>,
}
