// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// SSO connection details.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthenticationSSOStartedDataSSO {
    /// The ID of the organization.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub organization_id: Option<String>,
    /// The ID of the SSO connection.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub connection_id: Option<String>,
    /// The ID of the SSO session.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub session_id: Option<String>,
}
