// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthenticationChallengeVerifyResponse {
    /// The authentication challenge object.
    pub challenge: AuthenticationChallenge,
    /// Whether the code was valid.
    pub valid: bool,
}
