// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The connection with the expiring certificate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectionSAMLCertificateRenewalRequiredDataConnection {
    /// Unique identifier of the connection.
    pub id: String,
    /// The ID of the organization the connection belongs to.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub organization_id: Option<String>,
}
