// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectionSAMLCertificateRenewedData {
    /// The connection with the renewed certificate.
    pub connection: ConnectionSAMLCertificateRenewedDataConnection,
    /// The renewed SAML certificate details.
    pub certificate: ConnectionSAMLCertificateRenewedDataCertificate,
    /// An ISO 8601 timestamp.
    pub renewed_at: String,
}
