// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateObjectRequest {
    /// Map of values used to determine the encryption key.
    pub key_context: std::collections::HashMap<String, String>,
    /// Unique name for the object.
    pub name: String,
    /// Plaintext data to encrypt and store.
    pub value: String,
}
