// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateGroupRoleAssignment {
    /// The slug of the role to assign to the group.
    pub role_slug: String,
    /// The ID of the resource. Omit along with the external-id fields to target the organization itself.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub resource_id: Option<String>,
    /// The external ID of the resource.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub resource_external_id: Option<String>,
    /// The resource type slug.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub resource_type_slug: Option<String>,
}
