// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataIntegrationsVendCredentialsRequest {
    /// A [User](https://workos.com/docs/reference/authkit/user) identifier.
    pub user_id: String,
    /// An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub organization_id: Option<String>,
    /// A [connected account](https://workos.com/docs/reference/pipes/connected-account) identifier. Use this to select a specific connection when the user has several for this provider.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub connected_account_id: Option<String>,
}
