// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataIntegrationConfigurationResponse {
    /// Distinguishes the data integration configuration object.
    pub object: String,
    /// The unique identifier of the data integration.
    pub id: String,
    /// The [Organization](https://workos.com/docs/reference/organization) this configuration applies to.
    pub organization_id: String,
    /// The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
    pub slug: String,
    /// The display name of the data integration.
    pub name: String,
    /// Whether the integration is enabled for this organization. Reflects the organization override when one exists, otherwise the provider default.
    pub enabled: bool,
    /// The OAuth scopes in effect for this organization. Reflects the organization override when one is set, otherwise the provider scopes, or `null` when none are configured.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub scopes: Option<Vec<String>>,
    /// The timestamp when the configuration was created.
    pub created_at: String,
    /// The timestamp when the configuration was last updated.
    pub updated_at: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub credentials: Option<DataIntegrationCredentials>,
}
