// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DirectorySyncRateLimitError {
    /// The error code identifying the type of error.
    pub code: String,
    /// A human-readable description of the error.
    pub message: String,
    /// The number of seconds to wait before requesting another manual sync of this directory.
    pub retry_after_seconds: i64,
}
