// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DsyncGroupUserRemovedData {
    /// The ID of the directory.
    pub directory_id: String,
    /// The directory user removed from the group.
    pub user: DirectoryUser,
    /// The directory group the user was removed from.
    pub group: DirectoryGroup,
}
