// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DsyncGroupUserAddedData {
    /// The ID of the directory.
    pub directory_id: String,
    /// The directory user added to the group.
    pub user: DirectoryUser,
    /// The directory group the user was added to.
    pub group: DirectoryGroup,
}
