// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DsyncUserUpdatedDataEmail {
    /// Whether this is the primary email address.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub primary: Option<bool>,
    /// The type of email address.
    #[serde(rename = "type")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub type_: Option<String>,
    /// The email address value.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub value: Option<String>,
}
