// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailChange {
    /// Distinguishes the email change object.
    pub object: String,
    pub user: User,
    /// The new email address the user is changing to.
    pub new_email: String,
    /// The timestamp when the email change code expires.
    pub expires_at: String,
    /// The timestamp when the email change challenge was created.
    pub created_at: String,
}
