// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventList {
    /// Indicates this is a list response.
    pub object: String,
    /// The list of records for the current page.
    pub data: Vec<EventSchema>,
    /// Pagination cursor for navigating to the next page of results.
    pub list_metadata: EventListListMetadata,
}
