// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Additional context about the event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventContext {
    /// The Google Analytics client ID.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub google_analytics_client_id: Option<String>,
    /// The Google Analytics sessions associated with the event.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub google_analytics_sessions: Option<Vec<EventContextGoogleAnalyticsSession>>,
    /// The anonymous ID from analytics.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub ajs_anonymous_id: Option<String>,
    /// The client ID associated with the event.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub client_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub actor: Option<EventContextActor>,
    /// Attributes that changed from their previous values.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub previous_attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
}
