// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The actor who performed the action.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventContextActor {
    /// Unique identifier of the actor.
    pub id: String,
    /// The source of the actor that performed the action.
    pub source: EventContextActorSource,
    /// The name of the actor.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
}
