// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalAuthCompleteResponse {
    /// URI to redirect the user back to AuthKit to complete the OAuth flow.
    pub redirect_uri: String,
}
