// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Additional context about the event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlagCreatedContext {
    /// The client ID associated with the flag event.
    pub client_id: String,
    /// The actor who performed the action.
    pub actor: FlagCreatedContextActor,
}
