// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlagRuleUpdatedContextPreviousAttributeContextConfiguredTargetOrganization {
    /// The ID of the organization.
    pub id: String,
    /// The name of the organization.
    pub name: String,
}
