// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The configured targets for the flag rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlagRuleUpdatedContextConfiguredTarget {
    /// The organizations targeted by the flag rule.
    pub organizations: Vec<FlagRuleUpdatedContextConfiguredTargetOrganization>,
    /// The users targeted by the flag rule.
    pub users: Vec<FlagRuleUpdatedContextConfiguredTargetUser>,
}
