// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlagRuleUpdatedContextConfiguredTargetUser {
    /// The ID of the user.
    pub id: String,
    /// The email of the user.
    pub email: String,
}
