// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Group {
    /// The Group object.
    pub object: String,
    /// The unique ID of the Group.
    pub id: String,
    /// The ID of the Organization the Group belongs to.
    pub organization_id: String,
    /// The name of the Group.
    pub name: String,
    /// An optional description of the Group.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
    /// An ISO 8601 timestamp.
    pub created_at: String,
    /// An ISO 8601 timestamp.
    pub updated_at: String,
}
