// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InviteItContact {
    /// The Admin Portal features that the IT contact can configure.
    pub intents: Vec<InviteItContactIntents>,
}
