// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItContact {
    /// The IT Contact object.
    pub object: String,
    /// The unique ID of the IT Contact.
    pub id: String,
    /// The email address of the IT Contact.
    pub email: String,
    /// An ISO 8601 timestamp.
    pub created_at: String,
    /// An ISO 8601 timestamp.
    pub updated_at: String,
}
