// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// Cursor-based pagination metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListMetadata {
    /// Cursor for the next page of results.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// Cursor for the previous page of results.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub before: Option<String>,
}
