// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewConnectApplicationSecret {
    /// Distinguishes the connect application secret object.
    pub object: String,
    /// The unique ID of the client secret.
    pub id: String,
    /// A hint showing the last few characters of the secret value.
    pub secret_hint: String,
    /// The timestamp when the client secret was last used, or null if never used.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub last_used_at: Option<String>,
    /// An ISO 8601 timestamp.
    pub created_at: String,
    /// An ISO 8601 timestamp.
    pub updated_at: String,
    /// The plaintext secret value. Only returned at creation time and cannot be retrieved later.
    pub secret: String,
}
