// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrganizationDomainVerificationFailedData {
    /// The reason the domain verification failed.
    pub reason: OrganizationDomainVerificationFailedDataReason,
    /// The organization domain that failed verification.
    pub organization_domain: OrganizationDomainVerificationFailedDataOrganizationDomain,
}
