// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PasswordResetCreatedData {
    /// Distinguishes the password reset object.
    pub object: String,
    /// The unique ID of the password reset object.
    pub id: String,
    /// The unique ID of the user.
    pub user_id: String,
    /// The email address of the user.
    pub email: String,
    /// The timestamp when the password reset token expires.
    pub expires_at: String,
    /// The timestamp when the password reset token was created.
    pub created_at: String,
}
