// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PatchConnectionSAMLOptions {
    /// The Identity Provider metadata URL. When provided, the IdP fields and signing certificates are re-imported from the metadata document, replacing the current set. Mutually exclusive with the manual IdP fields. Set to `null` to stop tracking a metadata URL.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub idp_metadata_url: Option<String>,
    /// A custom Assertion Consumer Service (ACS) URL override. Set to `null` to revert to the standard WorkOS-generated ACS URL.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub acs_url: Option<String>,
    /// A custom Service Provider Entity ID (audience) override. Set to `null` to revert to the connection external key.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub sp_entity_id: Option<String>,
    /// The Identity Provider Entity ID.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub idp_entity_id: Option<String>,
    /// The Identity Provider SSO URL.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub idp_sso_url: Option<String>,
}
