// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RadarStandaloneDeleteRadarListEntryRequest {
    /// The value to remove from the list. Must match an existing entry.
    pub entry: String,
}
