// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RevokeSession {
    /// The ID of the session to revoke. This can be extracted from the `sid` claim of the access token.
    pub session_id: String,
}
