// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RoleCreatedData {
    /// Distinguishes the role object.
    pub object: String,
    /// The slug identifier of the role.
    pub slug: String,
    /// The slug of the resource type the role applies to.
    pub resource_type_slug: String,
    /// The permissions granted by the role.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub permissions: Option<Vec<String>>,
    /// An ISO 8601 timestamp.
    pub created_at: String,
    /// An ISO 8601 timestamp.
    pub updated_at: String,
}
