// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SAMLSpEncryptionCertificateList {
    pub object: String,
    /// Every Service Provider encryption certificate on the Connection, including expired ones.
    pub data: Vec<SAMLSpEncryptionCertificate>,
}
