// This file is auto-generated by oagen. Do not edit.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateUser {
    /// The email address of the user.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub email: Option<String>,
    /// The first name of the user.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub first_name: Option<String>,
    /// The last name of the user.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub last_name: Option<String>,
    /// The user's full name.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
    /// Whether the user's email has been verified.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub email_verified: Option<bool>,
    /// Object containing metadata key/value pairs associated with the user.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    /// The external ID of the user.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub external_id: Option<String>,
    /// The user's preferred locale.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub locale: Option<String>,
    /// The password to set for the user. Mutually exclusive with `password_hash`, `password_hash_type`, and `password_salt_position`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub password: Option<crate::SecretString>,
    /// The hashed password to set for the user. Required with `password_hash_type`. Mutually exclusive with `password`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub password_hash: Option<crate::SecretString>,
    /// The algorithm originally used to hash the password, used when providing a `password_hash`. Required with `password_hash`. Mutually exclusive with `password`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub password_hash_type: Option<UpdateUserPasswordHashType>,
    /// The position of the salt relative to the password when the `password_hash` digest was computed: `prefix` for `hash(salt + password)` or `suffix` for `hash(password + salt)`. Only supported with the `ssha256` hash type and only valid when a `password_hash` is provided. Defaults to `suffix`. Mutually exclusive with `password`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub password_salt_position: Option<UpdateUserPasswordSaltPosition>,
}
