// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserApiKeyCreatedDataOwner {
    /// The type of the API key owner.
    #[serde(rename = "type")]
    pub type_: String,
    /// The unique identifier of the user who owns the API key.
    pub id: String,
    /// The unique identifier of the organization the API key belongs to.
    pub organization_id: String,
}
