// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
/// The event payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VaultMetadataReadData {
    /// The unique identifier of the actor.
    pub actor_id: String,
    pub actor_source: VaultMetadataReadDataActorSource,
    /// The name of the actor.
    pub actor_name: String,
    /// The name of the key-value store.
    pub kv_name: String,
}
