// Code generated by oagen. DO NOT EDIT.

#[allow(unused_imports)]
use super::*;
#[allow(unused_imports)]
use crate::enums::*;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebhookEndpoint {
    /// Distinguishes the Webhook Endpoint object.
    pub object: String,
    /// Unique identifier of the Webhook Endpoint.
    pub id: String,
    /// The URL to which webhooks are sent.
    pub endpoint_url: String,
    /// The secret used to sign webhook payloads.
    pub secret: crate::SecretString,
    /// Whether the Webhook Endpoint is enabled or disabled.
    pub status: WebhookEndpointStatus,
    /// The events that the Webhook Endpoint is subscribed to.
    pub events: Vec<String>,
    /// An ISO 8601 timestamp.
    pub created_at: String,
    /// An ISO 8601 timestamp.
    pub updated_at: String,
}
